version: '3'
services:
  influxdb:
    image: influxdb
    container_name: influxdb2
    env_file:
      - influxdb.env
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: password 
      DOCKER_INFLUXDB_INIT_ORG: coe-psu
      DOCKER_INFLUXDB_INIT_BUCKET: itscoe-bucket
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: its-all-about-the-computer-engineering
    ports:
      - 8086:8086
    networks:
      - default
    volumes:
      - ./influxdb:/var/lib/influxdb2:rw
  
  mqtt-server:
    image: eclipse-mosquitto 
    container_name: mqtt-server
    ports:
      - 1883:1883
    networks:
      - default

  telegraf:
    image: telegraf:1.25-alpine
    depends_on:
      - influxdb
    volumes:
      - ./telegraf/mytelegraf.conf:/etc/telegraf/telegraf.conf:ro
    env_file:
      - influxdb.env
    networks:
      - default


networks:
  default:
